sudo: required

before_install:
  - source scripts/install.sh

before_script:
  - helm init --client-only

script:
  - helm lint
  - helm package .

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x scripts/deploy.sh && scripts/deploy.sh
  on:
    branch: master
    tags: true
