issuer:
  name: letsencrypt
  kind: Issuer
  environment: staging
  email: ivandelabeldad@gmail.com
  secret: letsencrypt-secret

certificate:
  name: rackian-cloud
  secret: rackian-cloud-certs
  commonName: '*.rackian.com'
  dnsNames:
    - rackian.com

ingress:
  name: rackian-cloud
  tls: enabled
  backend:
    serviceName: api-gateway
    servicePort: 80
  # hosts:
  # - host: api.rackian.com
  #   serviceName: api
  #   servicePort: 80
  # - host: staging.api.rackian.com
  #   serviceName: api-staging
  #   servicePort: 80
  # - host: accounts.rackian.com
  #   serviceName: accounts
  #   servicePort: 80
