apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rackian-cloud
  annotations:
    kubernetes.io/ingress.global-static-ip-name: rackian-cloud-ip
spec:
  {{- if eq .Values.ingress.tls "enabled" }}
  tls:
    - secretName: {{ .Values.certificate.secret }}
  {{- end }}
  {{- if .Values.ingress.backend }}
  backend:
    serviceName: {{ required "If backend is enabled it must have a serviceName" .Values.ingress.backend.serviceName }}
    servicePort: {{ required "If backend is enabled it must have a servicePort" .Values.ingress.backend.servicePort }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
          serviceName: {{ required "Hosts must have a serviceName" .serviceName }}
          servicePort: {{ required "Hosts must have a servicePort" .servicePort }}
  {{- end }}
